### ISSUE TITLE
NPC Roundup - Hutterites

### ISSUE THREAD

**Issue by sylae** [sylae/devilfish-map#10]
The Pineland Colony is our local collection of Hutterites. They largely keep to themselves but a couple of the leadership figures could use describing.

(For those unfamiliar, the Hutterites are a branch of Mennonites, basically imagine the Amish but a little more keen on technology. Typically they'll operate hugemassive farms, but nowadays some are moving into manufacturing.)

**Comment by Nashoid** [comment]
### The Pineland Colony

**Number of Residents:** Approximately 300

The Pineland Colony operates a number of sizable agricultural operations including such as _Farm-raised Turkey, Sweet Corn, Sugar Beets, Peas, Chicken/Eggs._  Since the colony functions as a collective unit, they can make or afford higher quality equipment, and can operate larger tracts of land, than if they were alone.

The Pineland colony, like most Hutterite colonies, function on the belief that everything is owned by the community, as a result personal belongings are few and far between for the most part.

Contrary to most assumptions that technology is totally shunned, the Majority of households have a television, and a radio, and a land-line phone, and lesser number of households have a family computer with a so-so internet connection. Some families may choose to forgo some of these things if they deem them too frivolous.

Phones in particular are used for both business and social purposes. Cell 'phones are also very common among all three groups to-day. Text messaging has made cell 'phones particularly useful for Hutterian young people wishing to keep in touch with their peers

In contrast to the uniformly plain look of the Amish and Old Order Mennonites, Hutterite clothing can be vividly colored, especially on children, although many Hutterites do wear plain dress. Most of the clothing is homemade within the colony. Shoes were homemade in the past but are now mostly store-bought.

The Pineland Colony utilizes a mix of traditional, and conventional education for their children. With much of the population choosing using a colony schoolhouse meet the educational requirements of the state of Minnesota. Optionally about 1/3rd of the colony chooses to send their children to public schools in Devilfish, some choosing to remove their children in 8th grade, and others choosing to finish all 12 grades of schooling. (with a small Minority who finish12th grade, that seeking a university degree.)

**Comment by Nashoid** [comment]
### Governance and Leadership:

The Pineland Colony maintains the traditional chain of command for a modern Hutterite Colony. It holds several high-ranking leadership Positions, all of which are Elected Positions.

**THE MINISTER:** The Minister or Prediger is also the chief executive and his duties include conducting church sermons, marriages, baptisms, funerals, disciplining members of the church and helping to manage the colony.

The Minister of the Pinelands Colony is named Daniel Kauffman, He is a man in his Forties, with dark brown hair, and a kind face, with more stress-lines than might be expected for his age, which can be attributed to violent death of his Predecessor, whom he was previously the assistant of.

He is quick to speak to the Devilfish city council to advocate and speak on the behalf of his Colony, making Minister Kaufmann a relatively frequent guest in city council meetings.

**THE ASSISTANT MINISTER:** Assisting the Minister in the management of church services, as the Head-Deacon. As well as acting as an assistant to the Teacher who runs the Colony Schoolhouse. As well as a number of other smaller duties to assist the management of the Colony.

The Assistant Minister for the Pineland Colony is a man named Isaiah Walter, who is the son of the previous Minister, who was killed a number of years ago. This has lead to resentment of those outside the Colony, but they tend to keep that resentment to themselves and close friends and family, as acting out against outsiders would give the Colony a bad name. 

**THE SECRETARY:** The Secretary is also commonly known as the 'Colony Manager' or the 'Business Boss' and is responsible for the Business operations of the Colony, including Book-keeping and Colony Budget.

The Secretary of the Pinelands Colony is an Gentleman in his Fifties, named Paul Wollman, who manages the business operations of the Colony, with great care and finesse. He is rather short Caucasian man, with greying black hair.  He is well-liked, known to be soft spoken, and humble to a fault. 

In the past, Paul has managed to secure lucrative business contracts for the Colony, leading to a running joke among the Colonists that he can see the future. He assures them that it is simply good-business practice, and the Lords blessing upon the Colony, that has insured the Colonies success.

**Comment by Nashoid** [comment]
### THE PINELAND COLONY
**Acres of Land:** 12,000 acres
**Number of Residents:** Approximately 300
The Pineland Colony operates a number of sizable agricultural operations including such as Farm-raised Turkey, Sweet Corn, Sugar Beets, Peas, Chicken/Eggs. Since the colony functions as a collective unit, they can make or afford higher quality equipment, and can operate larger tracts of land, than if they were alone.

**SUMMARY OF BELIEFS:**
Hutterites are insistent that all of life belongs under the lordship of Jesus. Along with beliefs in nonviolence and baptism following confession of faith, the radical economic practice of sharing goods in intentional community stems from this principle. All of Hutterite experience is fashioned in the context of this shared life.

The Pineland colony, like most Hutterite colonies, function on the belief that everything is owned by the community, as a result personal belongings are few and far between for the most part.

**COMMUNITY OF GOODS:**
Hutterites live in community, that is they share all of their possessions. All members living in one colony “own” the assets of that community collectively.  They work for each other and they don’t pay wages to their members. However, in lieu of wages all necessities of life are provided. So each member serves the other through their works and labour and all proceeds are shared.

People often ask to what extent Hutterites share their possessions. No, Hutterites, don’t share their toothbrushes and the like. All Hutterites keep some personal possessions which include personal effects. In addition, homes are private and household items within them are considered personal, although the colony may have provided them to begin with. But the houses, garages, barns, vehicles and machinery, successes and failures are all jointly owned by all members.

**THOUGHTS ON TECHNOLOGY:**
Contrary to most assumptions that technology is totally shunned, the Majority of households have a television, and a radio, and a land-line phone, and lesser number of households have a family computer with a so-so internet connection. Some families may choose to forgo some of these things if they deem them too frivolous.

Phones in particular are used for both business and social purposes. Cell 'phones are also very common among all three groups to-day. Text messaging has made cell 'phones particularly useful for Hutterian young people wishing to keep in touch with their peers

**HUTTERITE FASHION:**
In contrast to the uniformly plain look of the Amish and Old Order Mennonites, Hutterite clothing can be vividly colored, especially on children, although many Hutterites do wear plain dress. Most of the clothing is homemade within the colony. Shoes were homemade in the past but are now mostly store-bought.

**RECREATION**
Traditionally Hutterites had a very limited amount of leisure time. In addition, sports and other recreational pursuits were discouraged or banned and sometimes still are. However, attitudes towards leisure time is changing and many Hutterites do a lot of different things in their leisure time, depending on the mindset of their particular colony or church leaders. Many play sports, such as hockey, visit other colonies, work on crafts, read books and magazines, blog and create music.

**EDUCATION:**
The Pineland Colony utilizes a mix of traditional, and conventional education for their children. With much of the population choosing using a colony schoolhouse meet the educational requirements of the state of Minnesota. Optionally about 1/3rd of the colony chooses to send their children to public schools in Devilfish, some choosing to remove their children in 8th grade, and others choosing to finish all 12 grades of schooling. (with a small Minority who finish12th grade, that seeking a university degree.)

### GOVERNANCE AND LEADERSHIP

The Pineland Colony maintains the traditional chain of command for a modern Hutterite Colony. It holds several high-ranking leadership Positions, all of which are Elected Positions.

**THE MINISTER:**
The Minister or Prediger is also the chief executive and his duties include conducting church sermons, marriages, baptisms, funerals, disciplining members of the church and helping to manage the colony.

The Minister of the Pinelands Colony is named Daniel Kauffman, He is a man in his Forties, with dark brown hair, and a kind face, with more stress-lines than might be expected for his age, which can be attributed to violent death of his Predecessor, whom he was previously the assistant of.

He is quick to speak to the Devilfish city council to advocate and speak on the behalf of his Colony, making Minister Kaufmann a relatively frequent guest in city council meetings.

**THE ASSISTANT MINISTER:**
Assisting the Minister in the management of church services, as the Head-Deacon. As well as acting as an assistant to the Teacher who runs the Colony Schoolhouse. As well as a number of other smaller duties to assist the management of the Colony.

The Assistant Minister for the Pineland Colony is a man named Isaiah Walter, who is the son of the previous Minister, who was killed a number of years ago. This has lead to resentment of those outside the Colony, but they tend to keep that resentment to themselves and close friends and family, as acting out against outsiders would give the Colony a bad name.

**THE SECRETARY:**
The Secretary is also commonly known as the 'Colony Manager' or the 'Business Boss' and is responsible for the Business operations of the Colony, including Book-keeping and Colony Budget.

The Secretary of the Pinelands Colony is an Gentleman in his Fifties, named Paul Wollman, who manages the business operations of the Colony, with great care and finesse. He is rather short Caucasian man, with greying black hair. He is well-liked, known to be soft spoken, and humble to a fault.

In the past, Paul has managed to secure lucrative business contracts for the Colony, leading to a running joke among the Colonists that he can see the future. He assures them that it is simply good-business practice, and the Lords blessing upon the Colony, that has insured the Colonies success.

**Comment by sylae** [comment]
looks good to me! pending formal lore approval

**Comment by sylae** [comment]
Lore finds no issues, so we can go ahead and canonize this! If you have time, please post it it on the wiki under [Pineland Colony](https://wormrp.syl.ae/wiki/Pineland_Colony), making sure it has `{{devilfish}}` at the bottom (this is a navbox template I'll make in the future, for now it can just be a redlink tbh)
